[package]
name = "nexium-spirv"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
nexium-shader.workspace = true
rspirv.workspace = true
log.workspace = true
thiserror.workspace = true

[dev-dependencies]
naga.workspace = true
bytemuck.workspace = true
