#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Opcode {
    AL2P,
    ALD,
    AST,
    ATOM_cas,
    ATOM,
    ATOMS_cas,
    ATOMS,
    B2R,
    BAR,
    BFE_reg,
    BFE_cbuf,
    BFE_imm,
    BFI_reg,
    BFI_rc,
    BFI_cr,
    BFI_imm,
    BPT,
    BRA,
    BRK,
    BRX,
    CAL,
    CCTL,
    CCTLL,
    CONT,
    CS2R,
    CSET,
    CSETP,
    DADD_reg,
    DADD_cbuf,
    DADD_imm,
    DEPBAR,
    DFMA_reg,
    DFMA_rc,
    DFMA_cr,
    DFMA_imm,
    DMNMX_reg,
    DMNMX_cbuf,
    DMNMX_imm,
    DMUL_reg,
    DMUL_cbuf,
    DMUL_imm,
    DSET_reg,
    DSET_cbuf,
    DSET_imm,
    DSETP_reg,
    DSETP_cbuf,
    DSETP_imm,
    EXIT,
    F2F_reg,
    F2F_cbuf,
    F2F_imm,
    F2I_reg,
    F2I_cbuf,
    F2I_imm,
    FADD_reg,
    FADD_cbuf,
    FADD_imm,
    FADD32I,
    FCHK_reg,
    FCHK_cbuf,
    FCHK_imm,
    FCMP_reg,
    FCMP_rc,
    FCMP_cr,
    FCMP_imm,
    FFMA_reg,
    FFMA_rc,
    FFMA_cr,
    FFMA_imm,
    FFMA32I,
    FLO_reg,
    FLO_cbuf,
    FLO_imm,
    FMNMX_reg,
    FMNMX_cbuf,
    FMNMX_imm,
    FMUL_reg,
    FMUL_cbuf,
    FMUL_imm,
    FMUL32I,
    FSET_reg,
    FSET_cbuf,
    FSET_imm,
    FSETP_reg,
    FSETP_cbuf,
    FSETP_imm,
    FSWZADD,
    GETCRSPTR,
    GETLMEMBASE,
    HADD2_reg,
    HADD2_cbuf,
    HADD2_imm,
    HADD2_32I,
    HFMA2_reg,
    HFMA2_rc,
    HFMA2_cr,
    HFMA2_imm,
    HFMA2_32I,
    HMUL2_reg,
    HMUL2_cbuf,
    HMUL2_imm,
    HMUL2_32I,
    HSET2_reg,
    HSET2_cbuf,
    HSET2_imm,
    HSETP2_reg,
    HSETP2_cbuf,
    HSETP2_imm,
    I2F_reg,
    I2F_cbuf,
    I2F_imm,
    I2I_reg,
    I2I_cbuf,
    I2I_imm,
    IADD_reg,
    IADD_cbuf,
    IADD_imm,
    IADD3_reg,
    IADD3_cbuf,
    IADD3_imm,
    IADD32I,
    ICMP_reg,
    ICMP_rc,
    ICMP_cr,
    ICMP_imm,
    IDE,
    IDP_reg,
    IDP_imm,
    IMAD_reg,
    IMAD_rc,
    IMAD_cr,
    IMAD_imm,
    IMAD32I,
    IMADSP_reg,
    IMADSP_rc,
    IMADSP_cr,
    IMADSP_imm,
    IMNMX_reg,
    IMNMX_cbuf,
    IMNMX_imm,
    IMUL_reg,
    IMUL_cbuf,
    IMUL_imm,
    IMUL32I,
    IPA,
    ISBERD,
    ISCADD_reg,
    ISCADD_cbuf,
    ISCADD_imm,
    ISCADD32I,
    ISET_reg,
    ISET_cbuf,
    ISET_imm,
    ISETP_reg,
    ISETP_cbuf,
    ISETP_imm,
    JCAL,
    JMP,
    JMX,
    KIL,
    LD,
    LDC,
    LDG,
    LDL,
    LDS,
    LEA_hi_reg,
    LEA_hi_cbuf,
    LEA_lo_reg,
    LEA_lo_cbuf,
    LEA_lo_imm,
    LEPC,
    LONGJMP,
    LOP_reg,
    LOP_cbuf,
    LOP_imm,
    LOP3_reg,
    LOP3_cbuf,
    LOP3_imm,
    LOP32I,
    MEMBAR,
    MOV_reg,
    MOV_cbuf,
    MOV_imm,
    MOV32I,
    MUFU,
    NOP,
    OUT_reg,
    OUT_cbuf,
    OUT_imm,
    P2R_reg,
    P2R_cbuf,
    P2R_imm,
    PBK,
    PCNT,
    PEXIT,
    PIXLD,
    PLONGJMP,
    POPC_reg,
    POPC_cbuf,
    POPC_imm,
    PRET,
    PRMT_reg,
    PRMT_rc,
    PRMT_cr,
    PRMT_imm,
    PSET,
    PSETP,
    R2B,
    R2P_reg,
    R2P_cbuf,
    R2P_imm,
    RAM,
    RED,
    RET,
    RRO_reg,
    RRO_cbuf,
    RRO_imm,
    RTT,
    S2R,
    SAM,
    SEL_reg,
    SEL_cbuf,
    SEL_imm,
    SETCRSPTR,
    SETLMEMBASE,
    SHF_l_reg,
    SHF_l_imm,
    SHF_r_reg,
    SHF_r_imm,
    SHFL,
    SHL_reg,
    SHL_cbuf,
    SHL_imm,
    SHR_reg,
    SHR_cbuf,
    SHR_imm,
    SSY,
    ST,
    STG,
    STL,
    STP,
    STS,
    SUATOM,
    SUATOM_cas,
    SULD,
    SURED,
    SUST,
    SYNC,
    TEX,
    TEX_b,
    TEXS,
    TLD,
    TLD_b,
    TLD4,
    TLD4_b,
    TLD4S,
    TLDS,
    TMML,
    TMML_b,
    TXA,
    TXD,
    TXD_b,
    TXQ,
    TXQ_b,
    VABSDIFF,
    VABSDIFF4,
    VADD,
    VMAD,
    VMNMX,
    VOTE,
    VOTE_vtg,
    VSET,
    VSETP,
    VSHL,
    VSHR,
    XMAD_reg,
    XMAD_rc,
    XMAD_cr,
    XMAD_imm,
}

impl Opcode {
    pub fn name(self) -> &'static str {
        OPCODE_TABLE
            .iter()
            .find(|e| e.opcode == self)
            .map(|e| e.display)
            .unwrap_or("?")
    }
}

pub struct OpcodeEntry {
    pub opcode: Opcode,
    pub display: &'static str,
    pub encoding: &'static str,
}

pub const OPCODE_TABLE: &[OpcodeEntry] = &[
    OpcodeEntry {
        opcode: Opcode::AL2P,
        display: "AL2P",
        encoding: "1110 1111 1010 0---",
    },
    OpcodeEntry {
        opcode: Opcode::ALD,
        display: "ALD",
        encoding: "1110 1111 1101 1---",
    },
    OpcodeEntry {
        opcode: Opcode::AST,
        display: "AST",
        encoding: "1110 1111 1111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::ATOM_cas,
        display: "ATOM (cas)",
        encoding: "1110 1110 1111 ----",
    },
    OpcodeEntry {
        opcode: Opcode::ATOM,
        display: "ATOM",
        encoding: "1110 1101 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::ATOMS_cas,
        display: "ATOMS (cas)",
        encoding: "1110 1110 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::ATOMS,
        display: "ATOMS",
        encoding: "1110 1100 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::B2R,
        display: "B2R",
        encoding: "1111 0000 1011 1---",
    },
    OpcodeEntry {
        opcode: Opcode::BAR,
        display: "BAR",
        encoding: "1111 0000 1010 1---",
    },
    OpcodeEntry {
        opcode: Opcode::BFE_reg,
        display: "BFE (reg)",
        encoding: "0101 1100 0000 0---",
    },
    OpcodeEntry {
        opcode: Opcode::BFE_cbuf,
        display: "BFE (cbuf)",
        encoding: "0100 1100 0000 0---",
    },
    OpcodeEntry {
        opcode: Opcode::BFE_imm,
        display: "BFE (imm)",
        encoding: "0011 100- 0000 0---",
    },
    OpcodeEntry {
        opcode: Opcode::BFI_reg,
        display: "BFI (reg)",
        encoding: "0101 1011 1111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::BFI_rc,
        display: "BFI (rc)",
        encoding: "0101 0011 1111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::BFI_cr,
        display: "BFI (cr)",
        encoding: "0100 1011 1111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::BFI_imm,
        display: "BFI (imm)",
        encoding: "0011 011- 1111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::BPT,
        display: "BPT",
        encoding: "1110 0011 1010 ----",
    },
    OpcodeEntry {
        opcode: Opcode::BRA,
        display: "BRA",
        encoding: "1110 0010 0100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::BRK,
        display: "BRK",
        encoding: "1110 0011 0100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::BRX,
        display: "BRX",
        encoding: "1110 0010 0101 ----",
    },
    OpcodeEntry {
        opcode: Opcode::CAL,
        display: "CAL",
        encoding: "1110 0010 0110 ----",
    },
    OpcodeEntry {
        opcode: Opcode::CCTL,
        display: "CCTL",
        encoding: "1110 1111 011- ----",
    },
    OpcodeEntry {
        opcode: Opcode::CCTLL,
        display: "CCTLL",
        encoding: "1110 1111 100- ----",
    },
    OpcodeEntry {
        opcode: Opcode::CONT,
        display: "CONT",
        encoding: "1110 0011 0101 ----",
    },
    OpcodeEntry {
        opcode: Opcode::CS2R,
        display: "CS2R",
        encoding: "0101 0000 1100 1---",
    },
    OpcodeEntry {
        opcode: Opcode::CSET,
        display: "CSET",
        encoding: "0101 0000 1001 1---",
    },
    OpcodeEntry {
        opcode: Opcode::CSETP,
        display: "CSETP",
        encoding: "0101 0000 1010 0---",
    },
    OpcodeEntry {
        opcode: Opcode::DADD_reg,
        display: "DADD (reg)",
        encoding: "0101 1100 0111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::DADD_cbuf,
        display: "DADD (cbuf)",
        encoding: "0100 1100 0111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::DADD_imm,
        display: "DADD (imm)",
        encoding: "0011 100- 0111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::DEPBAR,
        display: "DEPBAR",
        encoding: "1111 0000 1111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::DFMA_reg,
        display: "DFMA (reg)",
        encoding: "0101 1011 0111 ----",
    },
    OpcodeEntry {
        opcode: Opcode::DFMA_rc,
        display: "DFMA (rc)",
        encoding: "0101 0011 0111 ----",
    },
    OpcodeEntry {
        opcode: Opcode::DFMA_cr,
        display: "DFMA (cr)",
        encoding: "0100 1011 0111 ----",
    },
    OpcodeEntry {
        opcode: Opcode::DFMA_imm,
        display: "DFMA (imm)",
        encoding: "0011 011- 0111 ----",
    },
    OpcodeEntry {
        opcode: Opcode::DMNMX_reg,
        display: "DMNMX (reg)",
        encoding: "0101 1100 0101 0---",
    },
    OpcodeEntry {
        opcode: Opcode::DMNMX_cbuf,
        display: "DMNMX (cbuf)",
        encoding: "0100 1100 0101 0---",
    },
    OpcodeEntry {
        opcode: Opcode::DMNMX_imm,
        display: "DMNMX (imm)",
        encoding: "0011 100- 0101 0---",
    },
    OpcodeEntry {
        opcode: Opcode::DMUL_reg,
        display: "DMUL (reg)",
        encoding: "0101 1100 1000 0---",
    },
    OpcodeEntry {
        opcode: Opcode::DMUL_cbuf,
        display: "DMUL (cbuf)",
        encoding: "0100 1100 1000 0---",
    },
    OpcodeEntry {
        opcode: Opcode::DMUL_imm,
        display: "DMUL (imm)",
        encoding: "0011 100- 1000 0---",
    },
    OpcodeEntry {
        opcode: Opcode::DSET_reg,
        display: "DSET (reg)",
        encoding: "0101 1001 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::DSET_cbuf,
        display: "DSET (cbuf)",
        encoding: "0100 1001 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::DSET_imm,
        display: "DSET (imm)",
        encoding: "0011 001- 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::DSETP_reg,
        display: "DSETP (reg)",
        encoding: "0101 1011 1000 ----",
    },
    OpcodeEntry {
        opcode: Opcode::DSETP_cbuf,
        display: "DSETP (cbuf)",
        encoding: "0100 1011 1000 ----",
    },
    OpcodeEntry {
        opcode: Opcode::DSETP_imm,
        display: "DSETP (imm)",
        encoding: "0011 011- 1000 ----",
    },
    OpcodeEntry {
        opcode: Opcode::EXIT,
        display: "EXIT",
        encoding: "1110 0011 0000 ----",
    },
    OpcodeEntry {
        opcode: Opcode::F2F_reg,
        display: "F2F (reg)",
        encoding: "0101 1100 1010 1---",
    },
    OpcodeEntry {
        opcode: Opcode::F2F_cbuf,
        display: "F2F (cbuf)",
        encoding: "0100 1100 1010 1---",
    },
    OpcodeEntry {
        opcode: Opcode::F2F_imm,
        display: "F2F (imm)",
        encoding: "0011 100- 1010 1---",
    },
    OpcodeEntry {
        opcode: Opcode::F2I_reg,
        display: "F2I (reg)",
        encoding: "0101 1100 1011 0---",
    },
    OpcodeEntry {
        opcode: Opcode::F2I_cbuf,
        display: "F2I (cbuf)",
        encoding: "0100 1100 1011 0---",
    },
    OpcodeEntry {
        opcode: Opcode::F2I_imm,
        display: "F2I (imm)",
        encoding: "0011 100- 1011 0---",
    },
    OpcodeEntry {
        opcode: Opcode::FADD_reg,
        display: "FADD (reg)",
        encoding: "0101 1100 0101 1---",
    },
    OpcodeEntry {
        opcode: Opcode::FADD_cbuf,
        display: "FADD (cbuf)",
        encoding: "0100 1100 0101 1---",
    },
    OpcodeEntry {
        opcode: Opcode::FADD_imm,
        display: "FADD (imm)",
        encoding: "0011 100- 0101 1---",
    },
    OpcodeEntry {
        opcode: Opcode::FADD32I,
        display: "FADD32I",
        encoding: "0000 10-- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::FCHK_reg,
        display: "FCHK (reg)",
        encoding: "0101 1100 1000 1---",
    },
    OpcodeEntry {
        opcode: Opcode::FCHK_cbuf,
        display: "FCHK (cbuf)",
        encoding: "0100 1100 1000 1---",
    },
    OpcodeEntry {
        opcode: Opcode::FCHK_imm,
        display: "FCHK (imm)",
        encoding: "0011 100- 1000 1---",
    },
    OpcodeEntry {
        opcode: Opcode::FCMP_reg,
        display: "FCMP (reg)",
        encoding: "0101 1011 1010 ----",
    },
    OpcodeEntry {
        opcode: Opcode::FCMP_rc,
        display: "FCMP (rc)",
        encoding: "0101 0011 1010 ----",
    },
    OpcodeEntry {
        opcode: Opcode::FCMP_cr,
        display: "FCMP (cr)",
        encoding: "0100 1011 1010 ----",
    },
    OpcodeEntry {
        opcode: Opcode::FCMP_imm,
        display: "FCMP (imm)",
        encoding: "0011 011- 1010 ----",
    },
    OpcodeEntry {
        opcode: Opcode::FFMA_reg,
        display: "FFMA (reg)",
        encoding: "0101 1001 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::FFMA_rc,
        display: "FFMA (rc)",
        encoding: "0101 0001 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::FFMA_cr,
        display: "FFMA (cr)",
        encoding: "0100 1001 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::FFMA_imm,
        display: "FFMA (imm)",
        encoding: "0011 001- 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::FFMA32I,
        display: "FFMA32I",
        encoding: "0000 11-- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::FLO_reg,
        display: "FLO (reg)",
        encoding: "0101 1100 0011 0---",
    },
    OpcodeEntry {
        opcode: Opcode::FLO_cbuf,
        display: "FLO (cbuf)",
        encoding: "0100 1100 0011 0---",
    },
    OpcodeEntry {
        opcode: Opcode::FLO_imm,
        display: "FLO (imm)",
        encoding: "0011 100- 0011 0---",
    },
    OpcodeEntry {
        opcode: Opcode::FMNMX_reg,
        display: "FMNMX (reg)",
        encoding: "0101 1100 0110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::FMNMX_cbuf,
        display: "FMNMX (cbuf)",
        encoding: "0100 1100 0110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::FMNMX_imm,
        display: "FMNMX (imm)",
        encoding: "0011 100- 0110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::FMUL_reg,
        display: "FMUL (reg)",
        encoding: "0101 1100 0110 1---",
    },
    OpcodeEntry {
        opcode: Opcode::FMUL_cbuf,
        display: "FMUL (cbuf)",
        encoding: "0100 1100 0110 1---",
    },
    OpcodeEntry {
        opcode: Opcode::FMUL_imm,
        display: "FMUL (imm)",
        encoding: "0011 100- 0110 1---",
    },
    OpcodeEntry {
        opcode: Opcode::FMUL32I,
        display: "FMUL32I",
        encoding: "0001 1110 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::FSET_reg,
        display: "FSET (reg)",
        encoding: "0101 1000 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::FSET_cbuf,
        display: "FSET (cbuf)",
        encoding: "0100 1000 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::FSET_imm,
        display: "FSET (imm)",
        encoding: "0011 000- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::FSETP_reg,
        display: "FSETP (reg)",
        encoding: "0101 1011 1011 ----",
    },
    OpcodeEntry {
        opcode: Opcode::FSETP_cbuf,
        display: "FSETP (cbuf)",
        encoding: "0100 1011 1011 ----",
    },
    OpcodeEntry {
        opcode: Opcode::FSETP_imm,
        display: "FSETP (imm)",
        encoding: "0011 011- 1011 ----",
    },
    OpcodeEntry {
        opcode: Opcode::FSWZADD,
        display: "FSWZADD",
        encoding: "0101 0000 1111 1---",
    },
    OpcodeEntry {
        opcode: Opcode::GETCRSPTR,
        display: "GETCRSPTR",
        encoding: "1110 0010 1100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::GETLMEMBASE,
        display: "GETLMEMBASE",
        encoding: "1110 0010 1101 ----",
    },
    OpcodeEntry {
        opcode: Opcode::HADD2_reg,
        display: "HADD2 (reg)",
        encoding: "0101 1101 0001 0---",
    },
    OpcodeEntry {
        opcode: Opcode::HADD2_cbuf,
        display: "HADD2 (cbuf)",
        encoding: "0111 101- 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HADD2_imm,
        display: "HADD2 (imm)",
        encoding: "0111 101- 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HADD2_32I,
        display: "HADD2_32I",
        encoding: "0010 110- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HFMA2_reg,
        display: "HFMA2 (reg)",
        encoding: "0101 1101 0000 0---",
    },
    OpcodeEntry {
        opcode: Opcode::HFMA2_rc,
        display: "HFMA2 (rc)",
        encoding: "0110 0--- 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HFMA2_cr,
        display: "HFMA2 (cr)",
        encoding: "0111 0--- 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HFMA2_imm,
        display: "HFMA2 (imm)",
        encoding: "0111 0--- 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HFMA2_32I,
        display: "HFMA2_32I",
        encoding: "0010 100- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HMUL2_reg,
        display: "HMUL2 (reg)",
        encoding: "0101 1101 0000 1---",
    },
    OpcodeEntry {
        opcode: Opcode::HMUL2_cbuf,
        display: "HMUL2 (cbuf)",
        encoding: "0111 100- 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HMUL2_imm,
        display: "HMUL2 (imm)",
        encoding: "0111 100- 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HMUL2_32I,
        display: "HMUL2_32I",
        encoding: "0010 101- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HSET2_reg,
        display: "HSET2 (reg)",
        encoding: "0101 1101 0001 1---",
    },
    OpcodeEntry {
        opcode: Opcode::HSET2_cbuf,
        display: "HSET2 (cbuf)",
        encoding: "0111 110- 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HSET2_imm,
        display: "HSET2 (imm)",
        encoding: "0111 110- 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HSETP2_reg,
        display: "HSETP2 (reg)",
        encoding: "0101 1101 0010 0---",
    },
    OpcodeEntry {
        opcode: Opcode::HSETP2_cbuf,
        display: "HSETP2 (cbuf)",
        encoding: "0111 111- 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::HSETP2_imm,
        display: "HSETP2 (imm)",
        encoding: "0111 111- 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::I2F_reg,
        display: "I2F (reg)",
        encoding: "0101 1100 1011 1---",
    },
    OpcodeEntry {
        opcode: Opcode::I2F_cbuf,
        display: "I2F (cbuf)",
        encoding: "0100 1100 1011 1---",
    },
    OpcodeEntry {
        opcode: Opcode::I2F_imm,
        display: "I2F (imm)",
        encoding: "0011 100- 1011 1---",
    },
    OpcodeEntry {
        opcode: Opcode::I2I_reg,
        display: "I2I (reg)",
        encoding: "0101 1100 1110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::I2I_cbuf,
        display: "I2I (cbuf)",
        encoding: "0100 1100 1110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::I2I_imm,
        display: "I2I (imm)",
        encoding: "0011 100- 1110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::IADD_reg,
        display: "IADD (reg)",
        encoding: "0101 1100 0001 0---",
    },
    OpcodeEntry {
        opcode: Opcode::IADD_cbuf,
        display: "IADD (cbuf)",
        encoding: "0100 1100 0001 0---",
    },
    OpcodeEntry {
        opcode: Opcode::IADD_imm,
        display: "IADD (imm)",
        encoding: "0011 100- 0001 0---",
    },
    OpcodeEntry {
        opcode: Opcode::IADD3_reg,
        display: "IADD3 (reg)",
        encoding: "0101 1100 1100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::IADD3_cbuf,
        display: "IADD3 (cbuf)",
        encoding: "0100 1100 1100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::IADD3_imm,
        display: "IADD3 (imm)",
        encoding: "0011 100- 1100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::IADD32I,
        display: "IADD32I",
        encoding: "0001 110- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::ICMP_reg,
        display: "ICMP (reg)",
        encoding: "0101 1011 0100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::ICMP_rc,
        display: "ICMP (rc)",
        encoding: "0101 0011 0100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::ICMP_cr,
        display: "ICMP (cr)",
        encoding: "0100 1011 0100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::ICMP_imm,
        display: "ICMP (imm)",
        encoding: "0011 011- 0100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::IDE,
        display: "IDE",
        encoding: "1110 0011 1001 ----",
    },
    OpcodeEntry {
        opcode: Opcode::IDP_reg,
        display: "IDP (reg)",
        encoding: "0101 0011 1111 1---",
    },
    OpcodeEntry {
        opcode: Opcode::IDP_imm,
        display: "IDP (imm)",
        encoding: "0101 0011 1101 1---",
    },
    OpcodeEntry {
        opcode: Opcode::IMAD_reg,
        display: "IMAD (reg)",
        encoding: "0101 1010 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::IMAD_rc,
        display: "IMAD (rc)",
        encoding: "0101 0010 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::IMAD_cr,
        display: "IMAD (cr)",
        encoding: "0100 1010 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::IMAD_imm,
        display: "IMAD (imm)",
        encoding: "0011 010- 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::IMAD32I,
        display: "IMAD32I",
        encoding: "1000 00-- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::IMADSP_reg,
        display: "IMADSP (reg)",
        encoding: "0101 1010 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::IMADSP_rc,
        display: "IMADSP (rc)",
        encoding: "0101 0010 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::IMADSP_cr,
        display: "IMADSP (cr)",
        encoding: "0100 1010 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::IMADSP_imm,
        display: "IMADSP (imm)",
        encoding: "0011 010- 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::IMNMX_reg,
        display: "IMNMX (reg)",
        encoding: "0101 1100 0010 0---",
    },
    OpcodeEntry {
        opcode: Opcode::IMNMX_cbuf,
        display: "IMNMX (cbuf)",
        encoding: "0100 1100 0010 0---",
    },
    OpcodeEntry {
        opcode: Opcode::IMNMX_imm,
        display: "IMNMX (imm)",
        encoding: "0011 100- 0010 0---",
    },
    OpcodeEntry {
        opcode: Opcode::IMUL_reg,
        display: "IMUL (reg)",
        encoding: "0101 1100 0011 1---",
    },
    OpcodeEntry {
        opcode: Opcode::IMUL_cbuf,
        display: "IMUL (cbuf)",
        encoding: "0100 1100 0011 1---",
    },
    OpcodeEntry {
        opcode: Opcode::IMUL_imm,
        display: "IMUL (imm)",
        encoding: "0011 100- 0011 1---",
    },
    OpcodeEntry {
        opcode: Opcode::IMUL32I,
        display: "IMUL32I",
        encoding: "0001 1111 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::IPA,
        display: "IPA",
        encoding: "1110 0000 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::ISBERD,
        display: "ISBERD",
        encoding: "1110 1111 1101 0---",
    },
    OpcodeEntry {
        opcode: Opcode::ISCADD_reg,
        display: "ISCADD (reg)",
        encoding: "0101 1100 0001 1---",
    },
    OpcodeEntry {
        opcode: Opcode::ISCADD_cbuf,
        display: "ISCADD (cbuf)",
        encoding: "0100 1100 0001 1---",
    },
    OpcodeEntry {
        opcode: Opcode::ISCADD_imm,
        display: "ISCADD (imm)",
        encoding: "0011 100- 0001 1---",
    },
    OpcodeEntry {
        opcode: Opcode::ISCADD32I,
        display: "ISCADD32I",
        encoding: "0001 01-- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::ISET_reg,
        display: "ISET (reg)",
        encoding: "0101 1011 0101 ----",
    },
    OpcodeEntry {
        opcode: Opcode::ISET_cbuf,
        display: "ISET (cbuf)",
        encoding: "0100 1011 0101 ----",
    },
    OpcodeEntry {
        opcode: Opcode::ISET_imm,
        display: "ISET (imm)",
        encoding: "0011 011- 0101 ----",
    },
    OpcodeEntry {
        opcode: Opcode::ISETP_reg,
        display: "ISETP (reg)",
        encoding: "0101 1011 0110 ----",
    },
    OpcodeEntry {
        opcode: Opcode::ISETP_cbuf,
        display: "ISETP (cbuf)",
        encoding: "0100 1011 0110 ----",
    },
    OpcodeEntry {
        opcode: Opcode::ISETP_imm,
        display: "ISETP (imm)",
        encoding: "0011 011- 0110 ----",
    },
    OpcodeEntry {
        opcode: Opcode::JCAL,
        display: "JCAL",
        encoding: "1110 0010 0010 ----",
    },
    OpcodeEntry {
        opcode: Opcode::JMP,
        display: "JMP",
        encoding: "1110 0010 0001 ----",
    },
    OpcodeEntry {
        opcode: Opcode::JMX,
        display: "JMX",
        encoding: "1110 0010 0000 ----",
    },
    OpcodeEntry {
        opcode: Opcode::KIL,
        display: "KIL",
        encoding: "1110 0011 0011 ----",
    },
    OpcodeEntry {
        opcode: Opcode::LD,
        display: "LD",
        encoding: "100- ---- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::LDC,
        display: "LDC",
        encoding: "1110 1111 1001 0---",
    },
    OpcodeEntry {
        opcode: Opcode::LDG,
        display: "LDG",
        encoding: "1110 1110 1101 0---",
    },
    OpcodeEntry {
        opcode: Opcode::LDL,
        display: "LDL",
        encoding: "1110 1111 0100 0---",
    },
    OpcodeEntry {
        opcode: Opcode::LDS,
        display: "LDS",
        encoding: "1110 1111 0100 1---",
    },
    OpcodeEntry {
        opcode: Opcode::LEA_hi_reg,
        display: "LEA (hi reg)",
        encoding: "0101 1011 1101 1---",
    },
    OpcodeEntry {
        opcode: Opcode::LEA_hi_cbuf,
        display: "LEA (hi cbuf)",
        encoding: "0001 10-- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::LEA_lo_reg,
        display: "LEA (lo reg)",
        encoding: "0101 1011 1101 0---",
    },
    OpcodeEntry {
        opcode: Opcode::LEA_lo_cbuf,
        display: "LEA (lo cbuf)",
        encoding: "0100 1011 1101 ----",
    },
    OpcodeEntry {
        opcode: Opcode::LEA_lo_imm,
        display: "LEA (lo imm)",
        encoding: "0011 011- 1101 0---",
    },
    OpcodeEntry {
        opcode: Opcode::LEPC,
        display: "LEPC",
        encoding: "0101 0000 1101 0---",
    },
    OpcodeEntry {
        opcode: Opcode::LONGJMP,
        display: "LONGJMP",
        encoding: "1110 0011 0001 ----",
    },
    OpcodeEntry {
        opcode: Opcode::LOP_reg,
        display: "LOP (reg)",
        encoding: "0101 1100 0100 0---",
    },
    OpcodeEntry {
        opcode: Opcode::LOP_cbuf,
        display: "LOP (cbuf)",
        encoding: "0100 1100 0100 0---",
    },
    OpcodeEntry {
        opcode: Opcode::LOP_imm,
        display: "LOP (imm)",
        encoding: "0011 100- 0100 0---",
    },
    OpcodeEntry {
        opcode: Opcode::LOP3_reg,
        display: "LOP3 (reg)",
        encoding: "0101 1011 1110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::LOP3_cbuf,
        display: "LOP3 (cbuf)",
        encoding: "0000 001- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::LOP3_imm,
        display: "LOP3 (imm)",
        encoding: "0011 11-- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::LOP32I,
        display: "LOP32I",
        encoding: "0000 01-- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::MEMBAR,
        display: "MEMBAR",
        encoding: "1110 1111 1001 1---",
    },
    OpcodeEntry {
        opcode: Opcode::MOV_reg,
        display: "MOV (reg)",
        encoding: "0101 1100 1001 1---",
    },
    OpcodeEntry {
        opcode: Opcode::MOV_cbuf,
        display: "MOV (cbuf)",
        encoding: "0100 1100 1001 1---",
    },
    OpcodeEntry {
        opcode: Opcode::MOV_imm,
        display: "MOV (imm)",
        encoding: "0011 100- 1001 1---",
    },
    OpcodeEntry {
        opcode: Opcode::MOV32I,
        display: "MOV32I",
        encoding: "0000 0001 0000 ----",
    },
    OpcodeEntry {
        opcode: Opcode::MUFU,
        display: "MUFU",
        encoding: "0101 0000 1000 0---",
    },
    OpcodeEntry {
        opcode: Opcode::NOP,
        display: "NOP",
        encoding: "0101 0000 1011 0---",
    },
    OpcodeEntry {
        opcode: Opcode::OUT_reg,
        display: "OUT (reg)",
        encoding: "1111 1011 1110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::OUT_cbuf,
        display: "OUT (cbuf)",
        encoding: "1110 1011 1110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::OUT_imm,
        display: "OUT (imm)",
        encoding: "1111 011- 1110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::P2R_reg,
        display: "P2R (reg)",
        encoding: "0101 1100 1110 1---",
    },
    OpcodeEntry {
        opcode: Opcode::P2R_cbuf,
        display: "P2R (cbuf)",
        encoding: "0100 1100 1110 1---",
    },
    OpcodeEntry {
        opcode: Opcode::P2R_imm,
        display: "P2R (imm)",
        encoding: "0011 1000 1110 1---",
    },
    OpcodeEntry {
        opcode: Opcode::PBK,
        display: "PBK",
        encoding: "1110 0010 1010 ----",
    },
    OpcodeEntry {
        opcode: Opcode::PCNT,
        display: "PCNT",
        encoding: "1110 0010 1011 ----",
    },
    OpcodeEntry {
        opcode: Opcode::PEXIT,
        display: "PEXIT",
        encoding: "1110 0010 0011 ----",
    },
    OpcodeEntry {
        opcode: Opcode::PIXLD,
        display: "PIXLD",
        encoding: "1110 1111 1110 1---",
    },
    OpcodeEntry {
        opcode: Opcode::PLONGJMP,
        display: "PLONGJMP",
        encoding: "1110 0010 1000 ----",
    },
    OpcodeEntry {
        opcode: Opcode::POPC_reg,
        display: "POPC (reg)",
        encoding: "0101 1100 0000 1---",
    },
    OpcodeEntry {
        opcode: Opcode::POPC_cbuf,
        display: "POPC (cbuf)",
        encoding: "0100 1100 0000 1---",
    },
    OpcodeEntry {
        opcode: Opcode::POPC_imm,
        display: "POPC (imm)",
        encoding: "0011 100- 0000 1---",
    },
    OpcodeEntry {
        opcode: Opcode::PRET,
        display: "PRET",
        encoding: "1110 0010 0111 ----",
    },
    OpcodeEntry {
        opcode: Opcode::PRMT_reg,
        display: "PRMT (reg)",
        encoding: "0101 1011 1100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::PRMT_rc,
        display: "PRMT (rc)",
        encoding: "0101 0011 1100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::PRMT_cr,
        display: "PRMT (cr)",
        encoding: "0100 1011 1100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::PRMT_imm,
        display: "PRMT (imm)",
        encoding: "0011 011- 1100 ----",
    },
    OpcodeEntry {
        opcode: Opcode::PSET,
        display: "PSET",
        encoding: "0101 0000 1000 1---",
    },
    OpcodeEntry {
        opcode: Opcode::PSETP,
        display: "PSETP",
        encoding: "0101 0000 1001 0---",
    },
    OpcodeEntry {
        opcode: Opcode::R2B,
        display: "R2B",
        encoding: "1111 0000 1100 0---",
    },
    OpcodeEntry {
        opcode: Opcode::R2P_reg,
        display: "R2P (reg)",
        encoding: "0101 1100 1111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::R2P_cbuf,
        display: "R2P (cbuf)",
        encoding: "0100 1100 1111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::R2P_imm,
        display: "R2P (imm)",
        encoding: "0011 100- 1111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::RAM,
        display: "RAM",
        encoding: "1110 0011 1000 ----",
    },
    OpcodeEntry {
        opcode: Opcode::RED,
        display: "RED",
        encoding: "1110 1011 1111 1---",
    },
    OpcodeEntry {
        opcode: Opcode::RET,
        display: "RET",
        encoding: "1110 0011 0010 ----",
    },
    OpcodeEntry {
        opcode: Opcode::RRO_reg,
        display: "RRO (reg)",
        encoding: "0101 1100 1001 0---",
    },
    OpcodeEntry {
        opcode: Opcode::RRO_cbuf,
        display: "RRO (cbuf)",
        encoding: "0100 1100 1001 0---",
    },
    OpcodeEntry {
        opcode: Opcode::RRO_imm,
        display: "RRO (imm)",
        encoding: "0011 100- 1001 0---",
    },
    OpcodeEntry {
        opcode: Opcode::RTT,
        display: "RTT",
        encoding: "1110 0011 0110 ----",
    },
    OpcodeEntry {
        opcode: Opcode::S2R,
        display: "S2R",
        encoding: "1111 0000 1100 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SAM,
        display: "SAM",
        encoding: "1110 0011 0111 ----",
    },
    OpcodeEntry {
        opcode: Opcode::SEL_reg,
        display: "SEL (reg)",
        encoding: "0101 1100 1010 0---",
    },
    OpcodeEntry {
        opcode: Opcode::SEL_cbuf,
        display: "SEL (cbuf)",
        encoding: "0100 1100 1010 0---",
    },
    OpcodeEntry {
        opcode: Opcode::SEL_imm,
        display: "SEL (imm)",
        encoding: "0011 100- 1010 0---",
    },
    OpcodeEntry {
        opcode: Opcode::SETCRSPTR,
        display: "SETCRSPTR",
        encoding: "1110 0010 1110 ----",
    },
    OpcodeEntry {
        opcode: Opcode::SETLMEMBASE,
        display: "SETLMEMBASE",
        encoding: "1110 0010 1111 ----",
    },
    OpcodeEntry {
        opcode: Opcode::SHF_l_reg,
        display: "SHF (l reg)",
        encoding: "0101 1011 1111 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SHF_l_imm,
        display: "SHF (l imm)",
        encoding: "0011 011- 1111 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SHF_r_reg,
        display: "SHF (r reg)",
        encoding: "0101 1100 1111 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SHF_r_imm,
        display: "SHF (r imm)",
        encoding: "0011 100- 1111 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SHFL,
        display: "SHFL",
        encoding: "1110 1111 0001 0---",
    },
    OpcodeEntry {
        opcode: Opcode::SHL_reg,
        display: "SHL (reg)",
        encoding: "0101 1100 0100 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SHL_cbuf,
        display: "SHL (cbuf)",
        encoding: "0100 1100 0100 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SHL_imm,
        display: "SHL (imm)",
        encoding: "0011 100- 0100 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SHR_reg,
        display: "SHR (reg)",
        encoding: "0101 1100 0010 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SHR_cbuf,
        display: "SHR (cbuf)",
        encoding: "0100 1100 0010 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SHR_imm,
        display: "SHR (imm)",
        encoding: "0011 100- 0010 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SSY,
        display: "SSY",
        encoding: "1110 0010 1001 ----",
    },
    OpcodeEntry {
        opcode: Opcode::ST,
        display: "ST",
        encoding: "101- ---- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::STG,
        display: "STG",
        encoding: "1110 1110 1101 1---",
    },
    OpcodeEntry {
        opcode: Opcode::STL,
        display: "STL",
        encoding: "1110 1111 0101 0---",
    },
    OpcodeEntry {
        opcode: Opcode::STP,
        display: "STP",
        encoding: "1110 1110 1010 0---",
    },
    OpcodeEntry {
        opcode: Opcode::STS,
        display: "STS",
        encoding: "1110 1111 0101 1---",
    },
    OpcodeEntry {
        opcode: Opcode::SUATOM,
        display: "SUATOM",
        encoding: "1110 1010 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::SUATOM_cas,
        display: "SUATOM_cas",
        encoding: "1110 1010 1--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::SULD,
        display: "SULD",
        encoding: "1110 1011 000- ----",
    },
    OpcodeEntry {
        opcode: Opcode::SURED,
        display: "SURED",
        encoding: "1110 1011 010- ----",
    },
    OpcodeEntry {
        opcode: Opcode::SUST,
        display: "SUST",
        encoding: "1110 1011 001- ----",
    },
    OpcodeEntry {
        opcode: Opcode::SYNC,
        display: "SYNC",
        encoding: "1111 0000 1111 1---",
    },
    OpcodeEntry {
        opcode: Opcode::TEX,
        display: "TEX",
        encoding: "1100 0--- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::TEX_b,
        display: "TEX (b)",
        encoding: "1101 1110 10-- ----",
    },
    OpcodeEntry {
        opcode: Opcode::TEXS,
        display: "TEXS",
        encoding: "1101 -00- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::TLD,
        display: "TLD",
        encoding: "1101 1100 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::TLD_b,
        display: "TLD (b)",
        encoding: "1101 1101 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::TLD4,
        display: "TLD4",
        encoding: "1100 10-- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::TLD4_b,
        display: "TLD4 (b)",
        encoding: "1101 1110 11-- ----",
    },
    OpcodeEntry {
        opcode: Opcode::TLD4S,
        display: "TLD4S",
        encoding: "1101 1111 -0-- ----",
    },
    OpcodeEntry {
        opcode: Opcode::TLDS,
        display: "TLDS",
        encoding: "1101 -01- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::TMML,
        display: "TMML",
        encoding: "1101 1111 0101 1---",
    },
    OpcodeEntry {
        opcode: Opcode::TMML_b,
        display: "TMML (b)",
        encoding: "1101 1111 0110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::TXA,
        display: "TXA",
        encoding: "1101 1111 0100 0---",
    },
    OpcodeEntry {
        opcode: Opcode::TXD,
        display: "TXD",
        encoding: "1101 1110 00-- ----",
    },
    OpcodeEntry {
        opcode: Opcode::TXD_b,
        display: "TXD (b)",
        encoding: "1101 1110 01-- ----",
    },
    OpcodeEntry {
        opcode: Opcode::TXQ,
        display: "TXQ",
        encoding: "1101 1111 0100 1---",
    },
    OpcodeEntry {
        opcode: Opcode::TXQ_b,
        display: "TXQ (b)",
        encoding: "1101 1111 0101 0---",
    },
    OpcodeEntry {
        opcode: Opcode::VABSDIFF,
        display: "VABSDIFF",
        encoding: "0101 0100 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::VABSDIFF4,
        display: "VABSDIFF4",
        encoding: "0101 0000 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::VADD,
        display: "VADD",
        encoding: "0010 00-- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::VMAD,
        display: "VMAD",
        encoding: "0101 1111 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::VMNMX,
        display: "VMNMX",
        encoding: "0011 101- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::VOTE,
        display: "VOTE",
        encoding: "0101 0000 1101 1---",
    },
    OpcodeEntry {
        opcode: Opcode::VOTE_vtg,
        display: "VOTE (vtg)",
        encoding: "0101 0000 1110 0---",
    },
    OpcodeEntry {
        opcode: Opcode::VSET,
        display: "VSET",
        encoding: "0100 000- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::VSETP,
        display: "VSETP",
        encoding: "0101 0000 1111 0---",
    },
    OpcodeEntry {
        opcode: Opcode::VSHL,
        display: "VSHL",
        encoding: "0101 0111 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::VSHR,
        display: "VSHR",
        encoding: "0101 0110 ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::XMAD_reg,
        display: "XMAD (reg)",
        encoding: "0101 1011 00-- ----",
    },
    OpcodeEntry {
        opcode: Opcode::XMAD_rc,
        display: "XMAD (rc)",
        encoding: "0101 0001 0--- ----",
    },
    OpcodeEntry {
        opcode: Opcode::XMAD_cr,
        display: "XMAD (cr)",
        encoding: "0100 111- ---- ----",
    },
    OpcodeEntry {
        opcode: Opcode::XMAD_imm,
        display: "XMAD (imm)",
        encoding: "0011 011- 00-- ----",
    },
];
