[package]
name = "nexium-nvdrv"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
nexium-shader.workspace = true
nexium-spirv.workspace = true
nexium-gpu = { path = "../nexium-gpu" }
nexium-common.workspace = true
nexium-memory.workspace = true
ash = "0.38"

log.workspace = true
bytemuck.workspace = true
zerocopy.workspace = true
modular-bitfield.workspace = true
bitflags.workspace = true
num_enum.workspace = true
byteorder.workspace = true
parking_lot.workspace = true
crossbeam.workspace = true
thiserror.workspace = true
once_cell.workspace = true
openh264 = "=0.5.0"
sha2 = "0.10"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
